name: Deploy to GCP

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.9.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Apply Terraform
      run: |
        cd terraform
        terraform apply -auto-approve
