name: Deploy to GCP

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Using the GCP Service Account Key from GitHub Secrets

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}  # Now using GitHub Variable for project ID
        install_components: gcloud

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Initialize Terraform
      env:
        GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}  # Using GitHub Variable for project ID
        GCP_REGION: ${{ vars.GCP_REGION }}          # Using GitHub Variable for region
        GCP_SERVICE_ACCOUNT_SECRET: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
      run: |
        cd terraform
        terraform init \
          -var="gcp_project_id=${GCP_PROJECT_ID}" \
          -var="gcp_region=${GCP_REGION}" \
          -var="gcp_service_account_secret=${GCP_SERVICE_ACCOUNT_SECRET}"

    - name: Apply Terraform
      env:
        GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}  # Using GitHub Variable for project ID
        GCP_REGION: ${{ vars.GCP_REGION }}          # Using GitHub Variable for region
        GCP_SERVICE_ACCOUNT_SECRET: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
      run: |
        cd terraform
        terraform apply -auto-approve \
          -var="gcp_project_id=${GCP_PROJECT_ID}" \
          -var="gcp_region=${GCP_REGION}" \
          -var="gcp_service_account_secret=${GCP_SERVICE_ACCOUNT_SECRET}"
